require: rubocop-rails
AllCops:
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Style/FrozenStringLiteralComment:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: false

Naming/FileName:
  Exclude:
    - config/_PUMA.rb
    - config/_SCHEDULE.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_GOOD_JOB.rb
Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
Rails/Output:
  Exclude:
    - db/seeds.rb
    - app/jobs/example_job.rb
    - app/models/currency_rate.rb
    - config/environments/development.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_GOOD_JOB.rb
