# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.1.2

workflows:
  build-docker-image-only-with-buildkit:
    jobs:
      - docker/publish:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          image: achris15/faenz
          remote-docker-version: 20.10.14
          update-description: true
          use-buildkit: true
