# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  docker: circleci/docker@2.1.2

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.0.4
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
      - run:
          name: 'Set tag version for docker build'
          command: export TAG_VERSION=$(cat version.txt)

workflows:
  build-and-publish-to-docker:
    jobs:
      - rspec
      - docker/publish:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          image: achris15/faenz
          tag: ${TAG_VERSION}
          remote-docker-version: 20.10.14
          use-buildkit: true
          requires:
            - rspec
