# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@2.1.4
  docker: circleci/docker@2.6.0

jobs:
  rspec:
    docker:
      - image: cimg/ruby:3.2.3
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

workflows:
  build-and-publish-to-docker:
    jobs:
      - rspec
      - docker/publish:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
          image: achris15/faenz
          tag: ${TAG_VERSION}
          use-buildkit: true
          requires:
            - rspec
          before_build:
            - run:
                name: 'export TAG_VERSION'
                command: echo "export TAG_VERSION=$(cat version.txt)" >> "$BASH_ENV"
